---
name: CI

"on":
  push:
    branches:
      - master
  pull_request:

env:
  CI_GENERIC_IMAGE: gitea.ttgrules.com/dev/generic:latest

jobs:
  pr-title-check:
    name: PR Title Check
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title uses conventional commit format
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          PATTERN='^[a-z]+(\([^)]+\))?(!)?: .+'
          if ! echo "${PR_TITLE}" | grep -Eq "${PATTERN}"; then
            echo "PR title must use Conventional Commits format"
            echo "(e.g. feat(scope): summary)."
            exit 1
          fi

  yaml-lint:
    name: YAML Lint
    runs-on: ubuntu-latest
    container:
      image: ${{ env.CI_GENERIC_IMAGE }}
      credentials:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - name: Show YAMLLint Version
        run: yamllint --version
      - name: YAMLLint
        run: yamllint --format github .

  json-validate:
    name: JSON Validate
    runs-on: ubuntu-latest
    container:
      image: ${{ env.CI_GENERIC_IMAGE }}
      credentials:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - name: Validate JSON files
        shell: bash
        run: |
          set -euo pipefail
          find . -type f -name '*.json' -not -path './.git/*' -print0 | \
            while IFS= read -r -d '' FILE; do
            echo "Validating ${FILE}"
            jq empty "${FILE}"
          done

  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    container:
      image: ${{ env.CI_GENERIC_IMAGE }}
      credentials:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - name: Setup Node
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 24
      - name: Check formatting
        run: npx --yes prettier --check "**/*.{json,md,mjs,yml,yaml}"

  perl-syntax:
    name: Perl Syntax Check
    runs-on: ubuntu-latest
    container:
      image: ${{ env.CI_GENERIC_IMAGE }}
      credentials:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - name: Check Perl syntax
        shell: bash
        run: |
          set -euo pipefail
          find . -type f \( -name '*.pl' -o -name '*.pm' -o -name '*.t' \) -not -path './.git/*' -print0 | while IFS= read -r -d '' FILE; do
            echo "Checking ${FILE}"
            perl -Ilib -c "${FILE}"
          done

  perl-tests:
    name: Perl Tests
    runs-on: ubuntu-latest
    container:
      image: ${{ env.CI_GENERIC_IMAGE }}
      credentials:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - name: Run module tests
        run: |
          perl Makefile.PL
          make test

  readme:
    name: README Up To Date
    runs-on: ubuntu-latest
    container:
      image: ${{ env.CI_GENERIC_IMAGE }}
      credentials:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - name: Regenerate README
        shell: bash
        run: |
          set -euo pipefail
          perl Makefile.PL
          make readme
      - name: Fail if README changed
        shell: bash
        run: |
          set -euo pipefail
          if ! git diff --quiet -- README.md; then
            echo "README.md is out of date. Run 'make readme' and commit the result."
            git --no-pager diff -- README.md
            exit 1
          fi

  renovate-config-validate:
    name: Renovate Config Validate
    runs-on: ubuntu-latest
    container:
      image: renovate/renovate
    needs:
      - json-validate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - name: Validate renovate.json
        run: renovate-config-validator renovate.json

  renovate-policy-check:
    name: Renovate Policy Check
    runs-on: ubuntu-latest
    container:
      image: ${{ env.CI_GENERIC_IMAGE }}
      credentials:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    needs:
      - renovate-config-validate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - name: Validate policy invariants
        shell: bash
        run: |
          set -euo pipefail
          jq -e '.["$schema"] == "https://docs.renovatebot.com/renovate-schema.json"' renovate.json >/dev/null
          jq -e '
            any(
              .packageRules[]?;
              .automerge == true and
              ((.matchUpdateTypes // []) | sort == ["digest","minor","patch","pin"])
            )
          ' renovate.json >/dev/null

  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    if: always()
    needs:
      - pr-title-check
      - yaml-lint
      - json-validate
      - format-check
      - perl-syntax
      - perl-tests
      - readme
      - renovate-config-validate
      - renovate-policy-check

    steps:
      - name: Enforce required check jobs
        shell: bash
        run: |
          set -euo pipefail
          REQUIRED_JOBS=(
            "yaml-lint:${{ needs.yaml-lint.result }}"
            "json-validate:${{ needs.json-validate.result }}"
            "format-check:${{ needs.format-check.result }}"
            "perl-syntax:${{ needs.perl-syntax.result }}"
            "perl-tests:${{ needs.perl-tests.result }}"
            "readme:${{ needs.readme.result }}"
            "renovate-config-validate:${{ needs.renovate-config-validate.result }}"
            "renovate-policy-check:${{ needs.renovate-policy-check.result }}"
          )

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            REQUIRED_JOBS+=("pr-title-check:${{ needs.pr-title-check.result }}")
          fi

          failed=0
          for item in "${REQUIRED_JOBS[@]}"; do
            job="${item%%:*}"
            result="${item#*:}"
            echo "${job}: ${result}"
            [ "${result}" = "success" ] || failed=1
          done

          [ "${failed}" -eq 0 ] || { echo "Quality gate failed"; exit 1; }

  release:
    name: Release
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    container:
      image: ${{ env.CI_GENERIC_IMAGE }}
      credentials:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    needs:
      - quality-gate
    outputs:
      released: ${{ steps.detect-release.outputs.released }}
      version: ${{ steps.detect-release.outputs.version }}
      tag: ${{ steps.detect-release.outputs.tag }}
      tarball: ${{ steps.detect-release.outputs.tarball }}
      has_dist_changes: ${{ steps.detect-dist-changes.outputs.has_dist_changes }}
      publish_pause: ${{ steps.detect-release.outputs.publish_pause }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 24
          cache: npm

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v5.0.3
        with:
          path: ./node_modules
          key: >-
            cache-node-modules-${{ runner.os }}-${{
            hashFiles('package-lock.json') }}
          restore-keys: |
            cache-node-modules-${{ runner.os }}-
            cache-node-modules-

      - name: Install dependencies
        run: |
          CACHE_HIT="${{ steps.cache-node-modules.outputs.cache-hit }}"
          if [ "${CACHE_HIT}" = "true" ]; then
            npm install
          else
            npm ci
          fi

      - name: Configure git author
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.local"

      - name: Configure authenticated origin
        run: |
          REMOTE_URL="${{ github.server_url }}/${{ github.repository }}.git"
          REMOTE_URL_WITH_TOKEN="$(echo "${REMOTE_URL}" | \
            sed "s|://|://${{ secrets.API_TOKEN_GITEA }}@|")"
          git remote set-url origin "${REMOTE_URL_WITH_TOKEN}"

      - name: Capture latest tag before release
        id: before-release
        run: |
          git fetch --tags --force
          PREV_TAG="$(git describe --tags --abbrev=0 2>/dev/null || true)"
          echo "tag=${PREV_TAG}" >> "${GITHUB_OUTPUT}"

      - name: Detect MANIFEST-tracked changes since last release
        id: detect-dist-changes
        shell: bash
        run: |
          set -euo pipefail
          PREV_TAG="${{ steps.before-release.outputs.tag }}"
          if [ -n "${PREV_TAG}" ]; then
            RANGE="${PREV_TAG}..HEAD"
          else
            FIRST_COMMIT="$(git rev-list --max-parents=0 HEAD)"
            RANGE="${FIRST_COMMIT}..HEAD"
          fi
          git diff --name-only "${RANGE}" | sort -u > /tmp/changed-files.txt
          sort -u MANIFEST > /tmp/manifest-files.txt
          if comm -12 /tmp/changed-files.txt /tmp/manifest-files.txt | grep -q .; then
            echo "has_dist_changes=true" >> "${GITHUB_OUTPUT}"
          else
            echo "has_dist_changes=false" >> "${GITHUB_OUTPUT}"
          fi

      - name: Debug release commit content
        shell: bash
        run: |
          set -euo pipefail
          git --no-pager status --short
          git --no-pager diff --name-status
          git --no-pager diff -- lib/Google/GeoCoder/Smart.pm

      - name: Run semantic-release
        env:
          GITEA_TOKEN: ${{ secrets.API_TOKEN_GITEA }}
          GITEA_URL: ${{ github.server_url }}
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.local
          GIT_COMMITTER_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.local
        run: npx semantic-release

      - name: Detect published release
        id: detect-release
        run: |
          git fetch --tags --force
          PREV_TAG="${{ steps.before-release.outputs.tag }}"
          NEW_TAG="$(git describe --tags --abbrev=0 2>/dev/null || true)"
          if [ -n "${NEW_TAG}" ] && [ "${NEW_TAG}" != "${PREV_TAG}" ]; then
            echo "released=true" >> "${GITHUB_OUTPUT}"
            echo "tag=${NEW_TAG}" >> "${GITHUB_OUTPUT}"
            echo "version=${NEW_TAG#v}" >> "${GITHUB_OUTPUT}"
            echo "tarball=Google-GeoCoder-Smart-${NEW_TAG#v}.tar.gz" >> "${GITHUB_OUTPUT}"
            if [ "${{ steps.detect-dist-changes.outputs.has_dist_changes }}" = "true" ]; then
              echo "publish_pause=true" >> "${GITHUB_OUTPUT}"
            else
              echo "publish_pause=false" >> "${GITHUB_OUTPUT}"
            fi
          else
            echo "released=false" >> "${GITHUB_OUTPUT}"
            echo "tag=" >> "${GITHUB_OUTPUT}"
            echo "version=" >> "${GITHUB_OUTPUT}"
            echo "tarball=" >> "${GITHUB_OUTPUT}"
            echo "publish_pause=false" >> "${GITHUB_OUTPUT}"
          fi

      - name: Upload distribution tarball artifact
        if: steps.detect-release.outputs.released == 'true'
        uses: https://github.com/christopherHX/gitea-upload-artifact@v4
        with:
          name: dist-tarball
          path: ${{ steps.detect-release.outputs.tarball }}
          if-no-files-found: error

  publish-pause:
    name: Publish to PAUSE
    if: needs.release.outputs.publish_pause == 'true'
    runs-on: ubuntu-latest
    container:
      image: ${{ env.CI_GENERIC_IMAGE }}
      credentials:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    needs:
      - release
    steps:
      - name: Download distribution tarball artifact
        uses: https://github.com/christopherHX/gitea-download-artifact@v4
        with:
          name: dist-tarball
          path: .

      - name: Guard existing PAUSE release
        shell: bash
        run: |
          set -euo pipefail
          VERSION="${{ needs.release.outputs.version }}"
          DIST_NAME="Google-GeoCoder-Smart-${VERSION}"
          STATUS_CODE="$(curl -sS -o /tmp/metacpan_release.json -w '%{http_code}' "https://fastapi.metacpan.org/v1/release/${DIST_NAME}")"
          if [ "${STATUS_CODE}" = "200" ]; then
            echo "PAUSE/MetaCPAN release ${DIST_NAME} already exists. Refusing re-upload."
            exit 1
          fi

      - name: Upload distribution to PAUSE
        shell: bash
        env:
          PAUSE_USERNAME: ${{ secrets.PAUSE_USERNAME }}
          PAUSE_PASSWORD: ${{ secrets.PAUSE_PASSWORD }}
        run: |
          set -euo pipefail
          VERSION="${{ needs.release.outputs.version }}"
          TARBALL="Google-GeoCoder-Smart-${VERSION}.tar.gz"
          if [ ! -f "${TARBALL}" ]; then
            echo "Expected tarball ${TARBALL} not found."
            exit 1
          fi
          PAUSE_RESPONSE_FILE="$(mktemp)"
          trap 'rm -f "${PAUSE_RESPONSE_FILE}"' EXIT
          PAUSE_HTTP_CODE="$(curl -sSL -o "${PAUSE_RESPONSE_FILE}" -w '%{http_code}' \
            -u "${PAUSE_USERNAME}:${PAUSE_PASSWORD}" \
            -F "HIDDENNAME=${PAUSE_USERNAME}" \
            -F "CAN_MULTIPART=1" \
            -F "pause99_add_uri_upload=@${TARBALL}" \
            "https://pause.perl.org/pause/authenquery?ACTION=add_uri")"
          if [ "${PAUSE_HTTP_CODE}" -ge 400 ]; then
            echo "PAUSE upload failed with HTTP ${PAUSE_HTTP_CODE}."
            cat "${PAUSE_RESPONSE_FILE}"
            exit 1
          fi
          if grep -qiE '<h2>[[:space:]]*Error[[:space:]]*</h2>|class="error_message"' "${PAUSE_RESPONSE_FILE}"; then
            echo "PAUSE upload failed: response contains an error message."
            cat "${PAUSE_RESPONSE_FILE}"
            exit 1
          fi
          if ! grep -qiE 'Query succeeded\.[[:space:]]*<b>[[:space:]]*Thank you for your contribution[[:space:]]*</b>|<p>[[:space:]]*Query succeeded\.' "${PAUSE_RESPONSE_FILE}"; then
            echo "PAUSE upload failed: response does not include a known success marker."
            cat "${PAUSE_RESPONSE_FILE}"
            exit 1
          fi
