---
name: Release

"on":
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version (must match module VERSION, e.g. 2.1.0)"
        required: true
        type: string

env:
  CI_GENERIC_IMAGE: gitea.ttgrules.com/dev/generic:latest

jobs:
  perl-tests:
    name: Perl Tests
    runs-on: ubuntu-latest
    container:
      image: ${{ env.CI_GENERIC_IMAGE }}
      credentials:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - name: Run module tests
        run: |
          perl Makefile.PL
          make test

  make-dist:
    name: Build distribution tarball
    runs-on: ubuntu-latest
    container:
      image: ${{ env.CI_GENERIC_IMAGE }}
      credentials:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    needs:
      - perl-tests
    if: ${{ github.ref == 'refs/heads/master' }}
    outputs:
      version: ${{ steps.version.outputs.version }}
      tarball: ${{ steps.dist.outputs.tarball }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - name: Determine release version
        id: version
        shell: bash
        run: |
          set -euo pipefail
          MODULE_VERSION="$(perl -Ilib -MGoogle::GeoCoder::Smart -e 'print $Google::GeoCoder::Smart::VERSION')"
          INPUT_VERSION="${{ github.event.inputs.release_version }}"
          if [[ -n "${INPUT_VERSION}" && "${INPUT_VERSION}" != "${MODULE_VERSION}" ]]; then
            echo "Input release_version (${INPUT_VERSION}) does not match module version (${MODULE_VERSION})."
            echo "Please bump \$VERSION in lib/Google/GeoCoder/Smart.pm and rerun."
            exit 1
          fi
          echo "version=${MODULE_VERSION}" >> "${GITHUB_OUTPUT}"
      - name: Build distribution tarball
        id: dist
        shell: bash
        run: |
          set -euo pipefail
          VERSION="${{ steps.version.outputs.version }}"
          TARBALL="Google-GeoCoder-Smart-${VERSION}.tar.gz"
          perl Makefile.PL
          make dist
          if [[ ! -f "${TARBALL}" ]]; then
            echo "Expected tarball ${TARBALL} not found."
            exit 1
          fi
          echo "tarball=${TARBALL}" >> "${GITHUB_OUTPUT}"
      - name: Upload distribution tarball artifact
        uses: https://github.com/christopherHX/gitea-upload-artifact@v4
        with:
          name: dist-tarball
          path: ${{ steps.dist.outputs.tarball }}
          if-no-files-found: error

  release:
    name: Create Tag and Release
    runs-on: ubuntu-latest
    container:
      image: ${{ env.CI_GENERIC_IMAGE }}
      credentials:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    needs:
      - make-dist
    if: ${{ github.ref == 'refs/heads/master' }}
    outputs:
      version: ${{ needs.make-dist.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - name: Download distribution tarball artifact
        uses: https://github.com/christopherHX/gitea-download-artifact@v4
        with:
          name: dist-tarball
          path: .
      - name: Guard existing tag
        shell: bash
        run: |
          set -euo pipefail
          git fetch --tags --force
          TAG="v${{ needs.make-dist.outputs.version }}"
          if git rev-parse -q --verify "refs/tags/${TAG}" >/dev/null; then
            echo "Tag ${TAG} already exists. Refusing to re-release."
            exit 1
          fi
      - name: Build release notes
        shell: bash
        run: |
          set -euo pipefail
          PREV_TAG="$(git describe --tags --abbrev=0 2>/dev/null || true)"
          {
            echo "Release v${{ needs.make-dist.outputs.version }}"
            echo
            if [[ -n "${PREV_TAG}" ]]; then
              echo "Changes since ${PREV_TAG}:"
              git log --no-merges --pretty='- %s' "${PREV_TAG}"..HEAD
            else
              echo "Initial tagged release for this repository."
              git log --no-merges --pretty='- %s'
            fi
          } > release-notes.txt
      - name: Create and push tag
        shell: bash
        env:
          API_TOKEN_GITEA: ${{ secrets.API_TOKEN_GITEA }}
        run: |
          set -euo pipefail
          TAG="v${{ needs.make-dist.outputs.version }}"
          git config user.name "gitea-actions[bot]"
          git config user.email "gitea-actions[bot]@users.noreply.local"
          git tag -a "${TAG}" -m "Release ${TAG}"
          REMOTE_URL="${{ github.server_url }}/${{ github.repository }}.git"
          REMOTE_URL_WITH_TOKEN="$(echo "${REMOTE_URL}" | sed "s|://|://${API_TOKEN_GITEA}@|")"
          git remote set-url origin "${REMOTE_URL_WITH_TOKEN}"
          git push origin "${TAG}"
      - name: Create Gitea release
        shell: bash
        env:
          API_TOKEN_GITEA: ${{ secrets.API_TOKEN_GITEA }}
        run: |
          set -euo pipefail
          TAG="v${{ needs.make-dist.outputs.version }}"
          TARBALL="${{ needs.make-dist.outputs.tarball }}"
          if [[ ! -f "${TARBALL}" ]]; then
            echo "Expected tarball ${TARBALL} not found."
            exit 1
          fi
          BODY_ESCAPED="$(jq -Rs . < release-notes.txt)"
          RELEASE_RESPONSE="$(curl -fsSL \
            -H "Authorization: token ${API_TOKEN_GITEA}" \
            -H "Content-Type: application/json" \
            -X POST \
            -d "{\"tag_name\":\"${TAG}\",\"target_commitish\":\"master\",\"name\":\"${TAG}\",\"body\":${BODY_ESCAPED},\"draft\":false,\"prerelease\":false}" \
            "${{ github.server_url }}/api/v1/repos/${{ github.repository }}/releases")"
          RELEASE_ID="$(echo "${RELEASE_RESPONSE}" | jq -r '.id')"
          if [[ -z "${RELEASE_ID}" || "${RELEASE_ID}" == "null" ]]; then
            echo "Could not determine release ID from API response."
            exit 1
          fi
          curl -fsSL \
            -H "Authorization: token ${API_TOKEN_GITEA}" \
            -X POST \
            -F "attachment=@${TARBALL}" \
            "${{ github.server_url }}/api/v1/repos/${{ github.repository }}/releases/${RELEASE_ID}/assets?name=${TARBALL}"

  publish-pause:
    name: Publish to PAUSE
    runs-on: ubuntu-latest
    container:
      image: ${{ env.CI_GENERIC_IMAGE }}
      credentials:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    needs:
      - release
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Download distribution tarball artifact
        uses: https://github.com/christopherHX/gitea-download-artifact@v4
        with:
          name: dist-tarball
          path: .
      - name: Guard existing PAUSE release
        shell: bash
        run: |
          set -euo pipefail
          VERSION="${{ needs.release.outputs.version }}"
          DIST_NAME="Google-GeoCoder-Smart-${VERSION}"
          STATUS_CODE="$(curl -sS -o /tmp/metacpan_release.json -w '%{http_code}' "https://fastapi.metacpan.org/v1/release/${DIST_NAME}")"
          if [[ "${STATUS_CODE}" == "200" ]]; then
            echo "PAUSE/MetaCPAN release ${DIST_NAME} already exists. Refusing re-upload."
            exit 1
          fi
      - name: Upload distribution to PAUSE
        shell: bash
        env:
          PAUSE_USERNAME: ${{ secrets.PAUSE_USERNAME }}
          PAUSE_PASSWORD: ${{ secrets.PAUSE_PASSWORD }}
        run: |
          set -euo pipefail
          VERSION="${{ needs.release.outputs.version }}"
          TARBALL="Google-GeoCoder-Smart-${VERSION}.tar.gz"
          if [[ ! -f "${TARBALL}" ]]; then
            echo "Expected tarball ${TARBALL} not found."
            exit 1
          fi
          PAUSE_RESPONSE_FILE="$(mktemp)"
          trap 'rm -f "${PAUSE_RESPONSE_FILE}"' EXIT
          PAUSE_HTTP_CODE="$(curl -sSL -o "${PAUSE_RESPONSE_FILE}" -w '%{http_code}' \
            -u "${PAUSE_USERNAME}:${PAUSE_PASSWORD}" \
            -F "HIDDENNAME=${PAUSE_USERNAME}" \
            -F "CAN_MULTIPART=1" \
            -F "pause99_add_uri_upload=@${TARBALL}" \
            "https://pause.perl.org/pause/authenquery?ACTION=add_uri")"
          if [[ "${PAUSE_HTTP_CODE}" -ge 400 ]]; then
            echo "PAUSE upload failed with HTTP ${PAUSE_HTTP_CODE}."
            cat "${PAUSE_RESPONSE_FILE}"
            exit 1
          fi
          if grep -qiE '<h2>[[:space:]]*Error[[:space:]]*</h2>|class="error_message"' "${PAUSE_RESPONSE_FILE}"; then
            echo "PAUSE upload failed: response contains an error message."
            cat "${PAUSE_RESPONSE_FILE}"
            exit 1
          fi
